name: Unlock Terraform

runs:
  using: composite
  steps:

    - name: remove lockfile
      id: remove-lockfile
      shell: bash
      run: |
        # remove-lockfile

        backend_bucket=${{ env.BACKEND_BUCKET }}
        state_key=${{ env.STATE_KEY }}
        lockfile="s3://${backend_bucket}/${state_key}.tflock"

        echo "removing lockfile ${lockfile}"

        aws s3 rm ${lockfile} > /dev/null 2&>1 || true
