name: Set environment from others

# TODO: resolve from-others; lift everything one level up

runs:
  using: composite
  steps:

    - name: checkout storm-library-for-terraform
      uses: actions/checkout@v6
      with:
        repository: stormreply/storm-library-for-terraform
        sparse-checkout: catalog.yaml

    - name: set catalog id
      id: set-catalog-id
      shell: bash
      run: |
        # set-environment/from-others/set-catalog-id
        status=$(
          cat catalog.yaml | jq '( .status // empty )' 2> /dev/null \
          || true
        ) # "|| true" is for jq can't parse - as it ought to be yaml
        # status is "" or HTTP error code
        if [ -n "$status" ] ; then
          cat catalog.yaml
          echo "::warn ::status from download call is $status. catalog id set to 42"
          echo "catalog_id=$catalog_id" >> $GITHUB_OUTPUT
          exit 0
        fi

        repository=${{ github.repository }}
        repo=${repository##*/}

        yq '.catalog["'${repo}'"]' catalog.yaml > catalog_item.yaml
        catalog_id=$(cat catalog_item.yaml | yq -r '.id // 42')
        if [ "$catalog_id" = "null" ] ; then
          echo "::warn ::${repo} or its id are not known to the catalog. catalog id set to 42."
          echo "catalog_id=$catalog_id" >> $GITHUB_OUTPUT
          exit 0
        fi

        cat << EOF | tee -a $GITHUB_ENV
        CATALOG_ID=$catalog_id
        EOF

    - name: set deployment tags
      id: set-deployment-tags
      shell: bash
      run: |
        # set-environment/from-others/set-deployment-tags

        catalog_reference="slt-${CATALOG_ID}"
        short_name="$catalog_reference"
        rm catalog.yaml

        repository=${{ github.repository }}
        repo=${repository##*/}

        long_name="${catalog_reference}-${repo}-${{ github.repository_owner }}"
        short_name="${short_name}-${{ github.repository_owner }}"
        state_file="${catalog_reference}.tfstate"
        state_key="modules/$repo/$state_file"

        cat << EOF | tee -a $GITHUB_ENV
        DEPLOYMENT_NAME=$long_name
        REPOSITORY=$repository
        REPO=$repo
        SHORT_NAME=$short_name
        STATE_KEY=$state_key
        EOF

    - name: set from defaults
      id: set-from-defaults
      shell: bash
      run: |
        # set-environment/from-others/set-from-defaults

        if [ -z "$BACKEND_ACCOUNT" ] ; then
          BACKEND_ACCOUNT=$(aws sts get-caller-identity | jq -r .Account)
        fi

        [ -z "$DEPLOYMENT_ACCOUNT" ] && DEPLOYMENT_ACCOUNT=$BACKEND_ACCOUNT
        [ -z "$DEPLOYMENT_REGION"  ] && DEPLOYMENT_REGION=$BACKEND_REGION

        cat << EOF >> $GITHUB_ENV
        BACKEND_ACCOUNT=$BACKEND_ACCOUNT
        BACKEND_ROLE=slt-0-storm-library-for-terraform-${{ github.repository_owner }}-backend
        DEPLOYMENT_ACCOUNT=$DEPLOYMENT_ACCOUNT
        DEPLOYMENT_REGION=$DEPLOYMENT_REGION
        DEPLOYMENT_ROLE=slt-0-storm-library-for-terraform-${{ github.repository_owner }}-deployment
        EOF

    - name: set backend bucket
      id: set-backend-bucket
      shell: bash
      run: |
        # set-environment/from-others/set-backend-bucket
        cat << EOF | tee -a $GITHUB_ENV
        BACKEND_BUCKET=storm-library-for-terraform-${{ github.repository_owner }}-$BACKEND_ACCOUNT
        EOF
