name: Set GITHUB_STEP_SUMMARY

runs:
  using: composite
  steps:

    - name: set-step-summary
      shell: bash
      run: |
        # set-environment/set-step-summary

        date >> $GITHUB_STEP_SUMMARY

        STATUS="OK"
        [ -z "$BACKEND_ACCOUNT"    ] && echo "::error ::Github repository variable BACKEND_ACCOUNT not set" && STATUS="ERROR"
        [ -z "$BACKEND_REGION"     ] && echo "::error ::Github repository variable BACKEND_REGION not set" && STATUS="ERROR"
        [ -z "$DEPLOYMENT_ACCOUNT" ] && echo "::error ::Github repository variable DEPLOYMENT_ACCOUNT not set" && STATUS="ERROR"
        [ -z "$DEPLOYMENT_REGION"  ] && echo "::error ::Github repository variable DEPLOYMENT_REGION not set" && STATUS="ERROR"
        echo "STATUS: [$STATUS]"

        cat << EOF >> $GITHUB_STEP_SUMMARY

        | ENVIRONMENT                   |                     |
        |:------------------------------|---------------------|
        EOF

        [ "${{ inputs.show }}" == "init" ] && cat << EOF >> $GITHUB_STEP_SUMMARY
        | ACCESS_DOMAIN                 | $ACCESS_DOMAIN      |
        | ACCESS_ROLE                   | $ACCESS_ROLE        |
        EOF

        cat << EOF >> $GITHUB_STEP_SUMMARY
        | BACKEND_ACCOUNT               | $BACKEND_ACCOUNT    |
        | BACKEND_BUCKET                | $BACKEND_BUCKET     |
        | BACKEND_REGION                | $BACKEND_REGION     |
        | BACKEND_ROLE                  | $BACKEND_ROLE       |
        | CATALOG_ID                    | $CATALOG_ID         |
        | DEPLOYMENT_ACCOUNT            | $DEPLOYMENT_ACCOUNT |
        | DEPLOYMENT_NAME               | $DEPLOYMENT_NAME    |
        | DEPLOYMENT_REGION             | $DEPLOYMENT_REGION  |
        | DEPLOYMENT_ROLE               | $DEPLOYMENT_ROLE    |
        EOF

        [ "${{ inputs.show }}" == "init" ] && cat << EOF >> $GITHUB_STEP_SUMMARY
        | OIDC_PRINCIPAL                | $OIDC_PRINCIPAL     |
        EOF

        cat << EOF >> $GITHUB_STEP_SUMMARY
        | REPO                          | $REPO               |
        | REPOSITORY                    | $REPOSITORY         |
        | SHORT_NAME                    | $SHORT_NAME         |
        | STATE_KEY                     | $STATE_KEY          |
        EOF

        [ "${{ inputs.show }}" == "init" ] && cat << EOF >> $GITHUB_STEP_SUMMARY
        | TERRAFORM_APP_ID              | $TERRAFORM_APP_ID   |
        EOF

        cat << EOF >> $GITHUB_STEP_SUMMARY
        | TOKEN_SHASUM                  | $TOKEN_SHASUM       |
        | TOKEN_TYPE                    | $TOKEN_TYPE         |
        EOF

        [ "$STATUS" = "OK" ] && exit 0 || exit 1
