name: Set GITHUB_STEP_SUMMARY

runs:
  using: composite
  steps:

    - name: set-step-summary
      shell: bash
      run: |
        # set-environment/set-step-summary

        date >> $GITHUB_STEP_SUMMARY

        STATUS="OK"
        [ -z "$BACKEND_ACCOUNT"    ] && echo "::error ::Github repository variable BACKEND_ACCOUNT not set" && STATUS="ERROR"
        [ -z "$BACKEND_REGION"     ] && echo "::error ::Github repository variable BACKEND_REGION not set" && STATUS="ERROR"
        [ -z "$DEPLOYMENT_ACCOUNT" ] && echo "::error ::Github repository variable DEPLOYMENT_ACCOUNT not set" && STATUS="ERROR"
        [ -z "$DEPLOYMENT_REGION"  ] && echo "::error ::Github repository variable DEPLOYMENT_REGION not set" && STATUS="ERROR"
        echo "STATUS: [$STATUS]"

        cat << EOF >> $GITHUB_STEP_SUMMARY

        <details>
        <summary><b>ENVIRONMENT</b></summary>

        | ENVIRONMENT                   |                     |
        |:------------------------------|---------------------|
        | BACKEND_ACCOUNT               | $BACKEND_ACCOUNT    |
        | BACKEND_BUCKET                | $BACKEND_BUCKET     |
        | BACKEND_REGION                | $BACKEND_REGION     |
        | BACKEND_ROLE                  | $BACKEND_ROLE       |
        | CATALOG_ID                    | $CATALOG_ID         |
        | DEPLOYMENT_ACCOUNT            | $DEPLOYMENT_ACCOUNT |
        | DEPLOYMENT_NAME               | $DEPLOYMENT_NAME    |
        | DEPLOYMENT_REGION             | $DEPLOYMENT_REGION  |
        | DEPLOYMENT_ROLE               | $DEPLOYMENT_ROLE    |
        | REPO                          | $REPO               |
        | REPOSITORY                    | $REPOSITORY         |
        | SHORT_NAME                    | $SHORT_NAME         |
        | STATE_KEY                     | $STATE_KEY          |

        </details>
        EOF

        [ "$STATUS" = "OK" ] && exit 0 || exit 1
