name: Inject Terraform backend

runs:
  using: composite
  steps:

    - name: inject Terraform backend
      shell: bash
      run: |
        # checkout/inject-backend
        cat << EOF > backend.tf
        terraform {
          backend "s3" {}
        }
        EOF
