name: Set environment from inputs

inputs:
  github_inputs:
    required: true

runs:
  using: composite
  steps:
    - name: set environment from inputs
      id: set-github-env-from-inputs
      shell: bash
      run: |
        # set-github-env/from-inputs
        github_inputs="${{ inputs.github_inputs }}"
        # echo "$github_inputs"
        IFS=$'\n' lines=($github_inputs)
        for l in "${lines[@]}" ; do
          key=${l%%:*}
          val=${l##*: }
          if [ -n "$val" ] ; then
            echo "$key=$val" | tee -a $GITHUB_ENV
          fi
        done
