name: Set deployment name

runs:
  using: composite
  steps:

    - name: checkout storm-library-for-terraform
      uses: actions/checkout@v4
      with:
        repository: stormreply/storm-library-for-terraform
        sparse-checkout: catalog.yaml

    - name: get catalog id
      id: get-catalog-id
      shell: bash
      run: |
        # set-environment/from-others/get-catalog-id
        status=$(
          cat catalog.yaml | jq '( .status // empty )' 2> /dev/null \
          || true
        ) # "|| true" is for jq can't parse - as it ought to be yaml
        # status is "" or HTTP error code
        if [ -n "$status" ] ; then
          cat catalog.yaml
          echo "::warn ::status from download call is $status. catalog id set to 42"
          echo "catalog_id=$catalog_id" >> $GITHUB_OUTPUT
          exit 0
        fi

        repository=${{ github.repository }}
        repo=${repository##*/}

        yq '.catalog["'${repo}'"]' catalog.yaml > catalog_item.yaml
        catalog_id=$(cat catalog_item.yaml | yq -r '.id // 42')
        if [ "$catalog_id" = "null" ] ; then
          echo "::warn ::${repo} or its id are not known to the catalog. catalog id set to 42."
          echo "catalog_id=$catalog_id" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "catalog_id=$catalog_id" >> $GITHUB_OUTPUT

    - name: set deployment name
      id: set-deployment-name
      shell: bash
      run: |
        # set-environment/from-others/set-deployment-name
        catalog_id=${{ steps.get-catalog-id.outputs.catalog_id }}

        catalog_reference="slt-${catalog_id}"
        short_name="$catalog_reference"
        rm catalog.yaml

        repository=${{ github.repository }}
        repo=${repository##*/}

        name="${catalog_reference}-${repo}-${{ github.actor }}"
        short_name="${short_name}-${{ github.actor }}"

        cat << EOF | tee -a $GITHUB_ENV
        CATALOG_ID=$catalog_id
        DEPLOYMENT_NAME=$name
        REPOSITORY=$repository
        REPO=$repo
        SHORT_NAME=$short_name
        EOF
