name: Check code

inputs:
  personal_access_token:
    required: false
  terraform_app_id:
    required: false
  terraform_private_key:
    required: false

runs:
  using: composite
  steps:

    - name: set token
      if: inputs.personal_access_token != '' || inputs.terraform_private_key != ''
      id: set-token
      uses: stormreply/slt-workflows/.github/actions/set-token@main
      with:
        personal_access_token: ${{ inputs.personal_access_token }}
        terraform_app_id: ${{ inputs.terraform_app_id }}
        terraform_private_key: ${{ inputs.terraform_private_key }}

    - name: checkout code
      uses: stormreply/slt-workflows/.github/actions/terraform/checkout@main

    - name: checkout support
      uses: actions/checkout@v6

    - name: show runner folder structure
      id: show-runner-folder-structure
      shell: bash
      run: |
        echo "pwd:"
        pwd
        echo "ls -la"
        ls -la
        echo "ls -la .."
        ls -la ..
