name: Set GITHUB_OUTPUT

outputs:
  env_json:
    value: ${{ steps.set-github-output.outputs.env_json }}

runs:
  using: composite
  steps:

    - name: set-github-output
      id: set-github-output
      shell: bash
      run: |
        # set-environment/set-github-output

        cat << EOF >> env.json
        {
          "BACKEND_ACCOUNT":    "$BACKEND_ACCOUNT",
          "BACKEND_BUCKET":     "$BACKEND_BUCKET",
          "BACKEND_REGION":     "$BACKEND_REGION",
          "BACKEND_ROLE":       "$BACKEND_ROLE",
          "CATALOG_ID":         "$CATALOG_ID",
          "DEPLOYMENT_ACCOUNT": "$DEPLOYMENT_ACCOUNT",
          "DEPLOYMENT_NAME":    "$DEPLOYMENT_NAME",
          "DEPLOYMENT_REGION":  "$DEPLOYMENT_REGION",
          "DEPLOYMENT_ROLE":    "$DEPLOYMENT_ROLE",
          "REPO":               "$REPO",
          "REPOSITORY":         "$REPOSITORY",
          "SHORT_NAME":         "$SHORT_NAME",
          "STATE_KEY":          "$STATE_KEY"
        }
        EOF

        env_json=$(cat env.json | jq -c)
        echo "env_json=$env_json"
        echo "env_json=$env_json" >> $GITHUB_OUTPUT
