name: Check files

inputs:
  exit_on_fail:
    required: false
  publish_badge:
    required: false

runs:
  using: composite
  steps:

    - name: checkout code
      uses: stormreply/slt-workflows/.github/actions/terraform/checkout@main

    - name: checkout support
      uses: actions/checkout@v6
      with:
        repository: stormreply/slt-repo-template
        path: slt-repo-template

    - name: check files
      id: check-files
      shell: bash
      run: |
        # check/files
        ./slt-repo-template/.support/check-files.sh && rc=0 || rc=$?
        [ $rc -ne 0 ] && echo "compliant=false" >> $GITHUB_OUTPUT || true

    - name: publish badge
      if: always() && inputs.publish_badge == 'true'
      uses: stormreply/slt-workflows/.github/actions/badges@main
      with:
        file: check-files.json
        label: "Check Files"
        message: ${{ steps.check-files.outputs.compliant == 'false' && 'failing' || 'passing' }}
        score: ${{ steps.check-files.outputs.compliant == 'false' && '0' || '1' }}

    - name: check failure
      if: steps.check-files.outputs.compliant == 'false' && inputs.exit_on_fail == 'true'
      shell: bash
      run: exit 1
