name: Set GITHUB_STEP_SUMMARY

runs:
  using: composite
  steps:

    - name: set-step-summary
      shell: bash
      run: |
        # set-github-env/set-step-summary

        date=$(date)

        STATUS="OK"
        [ -z "$BACKEND_ACCOUNT"    ] && echo "::error ::Github repository variable BACKEND_ACCOUNT not set" && STATUS="ERROR"
        [ -z "$BACKEND_REGION"     ] && echo "::error ::Github repository variable BACKEND_REGION not set" && STATUS="ERROR"
        [ -z "$DEPLOYMENT_ACCOUNT" ] && echo "::error ::Github repository variable DEPLOYMENT_ACCOUNT not set" && STATUS="ERROR"
        [ -z "$DEPLOYMENT_REGION"  ] && echo "::error ::Github repository variable DEPLOYMENT_REGION not set" && STATUS="ERROR"
        echo "STATUS: [$STATUS]"

        cat << EOF >> $GITHUB_STEP_SUMMARY

        <details>
        <summary>$date</summary>
        <br>

        ### Environment

        | VARIABLE                      | VALUE               |
        |:------------------------------|:--------------------|
        | BACKEND_ACCOUNT               | $BACKEND_ACCOUNT    |
        | BACKEND_BUCKET                | $BACKEND_BUCKET     |
        | BACKEND_REGION                | $BACKEND_REGION     |
        | BACKEND_ROLE                  | $BACKEND_ROLE       |
        | CATALOG_ID                    | $CATALOG_ID         |
        | DEPLOYMENT_ACCOUNT            | $DEPLOYMENT_ACCOUNT |
        | DEPLOYMENT_NAME               | $DEPLOYMENT_NAME    |
        | DEPLOYMENT_REGION             | $DEPLOYMENT_REGION  |
        | DEPLOYMENT_ROLE               | $DEPLOYMENT_ROLE    |
        | REPO                          | $REPO               |
        | REPOSITORY                    | $REPOSITORY         |
        | SHORT_NAME                    | $SHORT_NAME         |
        | STATE_KEY                     | $STATE_KEY          |
        EOF

        [ -n "$TOKEN" ] && cat << EOF >> $GITHUB_STEP_SUMMARY
        | TOKEN                         | $TOKEN              |
        | TOKEN_SHASUM                  | $TOKEN_SHASUM       |
        | TOKEN_TYPE                    | $TOKEN_TYPE         |
        EOF

        cat << EOF >> $GITHUB_STEP_SUMMARY
        </details>
        EOF

        [ "$STATUS" = "OK" ] && exit 0 || exit 1
