name: Check compliance

inputs:
  exit_on_fail:
    required: false
  publish_badge:
    required: false
  personal_access_token:
    required: false
  terraform_app_id:
    required: false
  terraform_private_key:
    required: false

runs:
  using: composite
  steps:

    - name: set token
      if: inputs.personal_access_token != '' || inputs.terraform_private_key != ''
      id: set-token
      uses: stormreply/slt-workflows/.github/actions/set-token@main
      with:
        personal_access_token: ${{ inputs.personal_access_token }}
        terraform_app_id: ${{ inputs.terraform_app_id }}
        terraform_private_key: ${{ inputs.terraform_private_key }}

    - name: checkout code
      uses: stormreply/slt-workflows/.github/actions/terraform/checkout@main

    - name: checkout support
      uses: actions/checkout@v6
      with:
        repository: stormreply/slt-repo-template
        path: slt-repo-template

    - name: set up python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - name: install dependencies
      shell: bash
      run: pip install --quiet boto3

    - name: check compliance
      id: check-compliance
      env:
        AWS_REGION: eu-central-1   # TODO: pass from workflow
        BEDROCK_MODEL_ID: eu.anthropic.claude-sonnet-4-6 # anthropic.claude-opus-4-7
        COMPLIANCE_FILE: ./slt-repo-template/.support/compliance.md
      shell: bash
      run: |
        # check/compliance
        python ./slt-repo-template/.support/check-compliance.py && rc=0 || rc=$?
        echo "RC $rc"
        [ $rc -ne 0 ] && echo "compliant=false" >> $GITHUB_OUTPUT

    - name: publish badge
      if: always() && inputs.publish_badge == 'true'
      uses: stormreply/slt-workflows/.github/actions/badges@main
      with:
        file: check-compliance.json
        label: "Check Compliance"
        message: ${{ steps.check-compliance.outputs.compliant == 'false' && 'failing' || 'passing' }}
        score: ${{ steps.check-compliance.outputs.compliant == 'false' && '0' || '1' }}

    - name: check failure
      if: steps.check-compliance.outputs.compliant == 'false' && inputs.exit_on_fail == 'true'
      shell: bash
      run: exit 1
