name: Destroy

runs:
  using: composite
  steps:

      - name: checkout code
        uses: stormreply/slt-workflows/.github/actions/terraform/checkout@main

      - name: terraform destroy
        uses: stormreply/slt-workflows/.github/actions/terraform/destroy@main
