name: Checkout Code

inputs:

  workflow:
    required: false
  infracost_api_key:
    required: false
  personal_access_token:
    required: false
  terraform_app_id:
    required: false
  terraform_private_key:
    required: false

runs:
  using: composite
  steps:

    - name: checkout repository
      uses: actions/checkout@v4

    - name: rewrite github URL (add x-access-token)
      uses: stormreply/slt-workflows/.github/actions/terraform/checkout/rewrite-github-url@main

    - name: inject provider.tf
      uses: stormreply/slt-workflows/.github/actions/terraform/checkout/inject-provider@main

    - name: inject backend.tf
      uses: stormreply/slt-workflows/.github/actions/terraform/checkout/inject-backend@main

    - name: inject metadata.tfvars
      uses: stormreply/slt-workflows/.github/actions/terraform/checkout/inject-metadata@main

    - name: inject init.tfvars
      if: inputs.init == 'true'
      uses: stormreply/slt-workflows/.github/actions/terraform/checkout/inject-init-tfvars@main

    - name: inject demo.tfvars
      if: vars.TFVARS != ''
      uses: stormreply/slt-workflows/.github/actions/terraform/checkout/inject-demo-tfvars@main

    - name: Set backend profile in AWS config
      uses: stormreply/slt-workflows/.github/actions/terraform/checkout/set-backend-profile@main
      with:
        use_oidc: ${{ inputs.workflow != 'configure' }}

    - name: Set deployment profile in AWS config
      uses: stormreply/slt-workflows/.github/actions/terraform/checkout/set-deployment-profile@main
      with:
        use_oidc: ${{ inputs.workflow != 'configure' }}

    - name: Check cost
      if: inputs.infracost_api_key != ''
      shell: bash
      run: |
        curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh
        export INFRACOST_API_KEY=${{ inputs.infracost_api_key }}
        # infracost breakdown --path . --format json 2> /dev/null | jq .
        thc=$(infracost breakdown --path . --format json 2> /dev/null | jq -r .totalHourlyCost)
        thc=$(printf "%.2f" $thc)
        tmc=$(infracost breakdown --path . --format json 2> /dev/null | jq -r .totalMonthlyCost)
        tmc=$(printf "%.2f" $tmc)
        echo "The total estimated static hourly cost of this deployment is $thc USD. Monthly: $tmc USD" >> $GITHUB_STEP_SUMMARY
