name: Init

inputs:
  infracost_api_key:
    required: false

runs:
  using: composite
  steps:

    - name: checkout code
      uses: stormreply/slt-workflows/.github/actions/terraform/checkout@main
      with:
        infracost_api_key: ${{ inputs.infracost_api_key }}

    - name: terraform plan
      uses: stormreply/slt-workflows/.github/actions/terraform/plan@main
