name: Execute

runs:
  using: composite
  steps:

    - name: Execute
      shell: bash
      run: |
        # scheduler/execute

        echo EXECUTE
        echo

        for job in $(cat /tmp/selected) ; do

          file=${job##*/} ; f=${file}
          date=${f%%.*} ; f=${f##$date.}
          time=${f%%.*} ; f=${f##$time.}
          action=${f%%.*} ; f=${f##$action.}
          account_id=${f%%.*} ; f=${f##$account_id.}
          region=${f%%.*} ; f=${f##$region.}
          repo=${f%%.*} ; f=${f##$repo.}

          printf "%-8s %-6s %-7s %-12s %-15s %-15s %-s\n" \
            "DATE" "TIME" "ACTION" "ACCOUNT_ID" "REGION" "REPO"
          printf "%-8s %-6s %-7s %-12s %-15s %-15s %-s\n" \
            "$date" "$time" "$action" "$account_id" "$region" "$repo"

          repository="${{ github.repository_owner }}/$repo"

          aws s3 cp \
            s3://${{ env.BACKEND_BUCKET }}/schedule/$file \
            /tmp \
            --quiet

          cat << EOF
        cat /tmp/$file | gh workflow run ${action}.yaml --repo "$repository" --json
        EOF

          cat /tmp/$file \
          | gh workflow run ${action}.yaml --repo "$repository" --json 2>&1 \
          | tee /tmp/$job &

        done

        echo
        echo now show job output
        echo

        for job in $(cat /tmp/selected) ; do
          ls -la /tmp/$job
        done
