name: Set token

inputs:
  github_token:
    required: false
  personal_access_token:
    required: false
  terraform_app_id:
    required: false
  terraform_private_key:
    required: false

runs:
  using: composite
  steps:

    - name: check token
      shell: bash
      id: check-token
      run: |
        # set-token/check-token
        if [ -z "${{ inputs.personal_access_token }}" -a -z "${{ inputs.terraform_private_key }}" ] ; then
          echo "::error ::It seems like you have no valid token."
          exit 1
        fi

    - name: set token parameters
      shell: bash
      id: set-token-parameters
      run: |
        # set-token/set-token-parameters
        cat << EOF >> $GITHUB_ENV
        GITHUB_TOKEN=${{ inputs.github_token }}
        PERSONAL_ACCESS_TOKEN=${{ inputs.personal_access_token }}
        TERRAFORM_APP_ID=${{ inputs.terraform_app_id }}
        TERRAFORM_PRIVATE_KEY<<EOK
        ${{ inputs.terraform_private_key }}
        EOK
        EOF

    - name: create github app token
      if: env.TERRAFORM_APP_ID != '' && env.TERRAFORM_PRIVATE_KEY != ''
      id: create-github-app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ env.TERRAFORM_APP_ID }}
        private-key: ${{ env.TERRAFORM_PRIVATE_KEY }}
        owner: ${{ github.repository_owner }}

    - name: set Token
      id: set-token
      shell: bash
      run: |
        # set-token/set-token

        type="Github App Token" # so far
        token="${{ steps.create-github-app-token.outputs.token }}"

        if [ -z "${token}" ] ; then
          token=${{ env.PERSONAL_ACCESS_TOKEN }}
          type="Personal Access Token"
        fi

        if [ -z "${token}" ] ; then
          token=${{ env.GITHUB_TOKEN }}
          type="GITHUB_TOKEN"
        fi

        if [ ${#token} -eq 0 ] ; then
          echo "::error title=No valid token::could not get a token"
          exit 1
        fi

        echo "::notice ::using your $type as token"

        echo $token_shasum="$(echo "$token" | shasum | awk '{ print $1 }')"

        cat << EOF | tee -a $GITHUB_ENV
        TOKEN=$token
        TOKEN_SHASUM=$token_shasum
        TOKEN_TYPE=$type
        EOF
