name: Save variables

inputs:
  repository:
    required: true

runs:
  using: composite
  steps:

    - name: save AWS access domain
      id: save-aws-access-domain
      uses: stormreply/slt-workflows/.github/actions/configure/init/save-variable@main
      with:
        repository: ${{ github.repository }}
        value: ${{ env.ACCESS_DOMAIN }}
        variable: ACCESS_DOMAIN

    - name: save AWS access role
      id: save-aws-access-role
      uses: stormreply/slt-workflows/.github/actions/configure/init/save-variable@main
      with:
        repository: ${{ github.repository }}
        value: ${{ env.ACCESS_ROLE }}
        variable: ACCESS_ROLE

    - name: save backend account
      id: save-backend-account
      uses: stormreply/slt-workflows/.github/actions/configure/init/save-variable@main
      with:
        repository: ${{ github.repository }}
        value: ${{ env.BACKEND_ACCOUNT }}
        variable: BACKEND_ACCOUNT

    - name: save backend bucket
      id: save-backend-bucket
      uses: stormreply/slt-workflows/.github/actions/configure/init/save-variable@main
      with:
        repository: ${{ github.repository }}
        value: ${{ env.BACKEND_BUCKET }}
        variable: BACKEND_BUCKET

    - name: save backend region
      id: save-backend-region
      uses: stormreply/slt-workflows/.github/actions/configure/init/save-variable@main
      with:
        repository: ${{ github.repository }}
        value: ${{ env.BACKEND_REGION }}
        variable: BACKEND_REGION

    - name: save deployment account
      id: save-deployment-account
      uses: stormreply/slt-workflows/.github/actions/configure/init/save-variable@main
      with:
        repository: ${{ github.repository }}
        value: ${{ env.DEPLOYMENT_ACCOUNT }}
        variable: DEPLOYMENT_ACCOUNT

    - name: save deployment name
      id: save-deployment-name
      uses: stormreply/slt-workflows/.github/actions/configure/init/save-variable@main
      with:
        repository: ${{ github.repository }}
        value: ${{ env.DEPLOYMENT_NAME }}
        variable: DEPLOYMENT_NAME

    - name: save deployment region
      id: save-deployment-region
      uses: stormreply/slt-workflows/.github/actions/configure/init/save-variable@main
      with:
        repository: ${{ github.repository }}
        value: ${{ env.DEPLOYMENT_REGION }}
        variable: DEPLOYMENT_REGION

    - name: save OIDC principal
      id: save-oidc-principal
      uses: stormreply/slt-workflows/.github/actions/configure/init/save-variable@main
      with:
        repository: ${{ github.repository }}
        value: ${{ env.OIDC_PRINCIPAL }}
        variable: OIDC_PRINCIPAL

    - name: save short name
      id: save-short-name
      uses: stormreply/slt-workflows/.github/actions/configure/init/save-variable@main
      with:
        repository: ${{ github.repository }}
        value: ${{ env.SHORT_NAME }}
        variable: SHORT_NAME
