name: Save variable

inputs:
  repository:
    required: false
    default: ${{ github.repository }}
  value:
    required: true
  variable:
    required: true

runs:
  using: composite
  steps:
    - name: Set repository variable
      shell: bash
      env:
      run: |
        # configure/init/save-variable vars.${{ inputs.variable }} from ${{ inputs.repository }}
        repo=${{ inputs.repository }}
        token=${{ env.TOKEN }} # TODO:
        variable=${{ inputs.variable }}
        value=${{ inputs.value }}
        output=$(
          curl -X PATCH \
            -H "Authorization: Bearer $token" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$repo/actions/variables/$variable \
            -d "{\"name\":\"$variable\", \"value\":\"$value\"}" \
            -f \
          2> /dev/null \
          || \
          curl -X POST \
            -H "Authorization: Bearer $token" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$repo/actions/variables \
            -d "{\"name\":\"$variable\", \"value\":\"$value\"}" \
          2> /dev/null
        )
        status=$(echo "$output" | jq '( .status // empty )')
        # status is "" or HTTP error code
        if [ -n "$status" ] ; then
          echo "$output"
          echo "::error ::Status from set-variable call is $status."
          echo "::error ::Your $TOKEN_TYPE likely does not have sufficient permissions."
          exit 1
        fi
        echo "Set vars.$variable=$value in $repo"
