name: Terraform apply

runs:
  using: composite
  steps:

    - name: Download tfplan
      uses: actions/download-artifact@v8
      with:
        name: tfplan

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4

    - name: Terraform init with S3 backend
      shell: bash
      run: |
        # terraform init
        terraform init \
          -backend-config="bucket=${{ env.BACKEND_BUCKET }}" \
          -backend-config="profile=backend" \
          -backend-config="key=${{ env.STATE_KEY }}" \
          -backend-config="region=${{ env.BACKEND_REGION }}" \
          -backend-config="use_lockfile=true"

    - name: Terraform apply
      shell: bash
      run: |
        # terraform/apply
        unset AWS_SECRET_ACCESS_KEY
        unset AWS_SESSION_TOKEN
        unset AWS_ACCESS_KEY_ID

        export AWS_PROFILE=deployment
        echo "AWS_PROFILE=deployment" >> $GITHUB_ENV

        terraform version
        terraform apply \
          -input=false \
          -auto-approve \
          tfplan

    - name: Check for artifact
      shell: bash
      run: |
        # check for artifact
        set +e
        artifact=$(terraform output -raw artifact 2> /dev/null)
        if [ $? -eq 0 ] ; then
          echo "ARTIFACT: [$artifact]"
          echo "ARTIFACT=${artifact}" >> $GITHUB_ENV
        fi
        set -e

    - name: Upload artifact
      if: env.ARTIFACT != ''
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.ARTIFACT }}
        path: ${{ env.ARTIFACT }}

    - name: Check for summary output
      shell: bash
      run: |
        # check for summary output
        set +e
        summary=$(terraform output -json _summary 2> /dev/null)
        if [ $? -eq 0 ] ; then
          cat << EOF >> $GITHUB_STEP_SUMMARY
        <b>OUTPUT</b>

        EOF
          echo "$summary" | jq -c 'to_entries[]' | while read -r entry; do
            key=$(echo "$entry" | jq -r '.key')
            value=$(echo "$entry" | jq -r '.value')

            cat << EOF >> $GITHUB_STEP_SUMMARY
        <b>$key</b>
        $value

        EOF
          done
        fi
        set -e
