name: AWS Login

inputs:
  region:
    required: true
    description: "AWS Region"

runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.region }}

    - name: Verify AWS Identity
      shell: bash
      run: |
        echo "Verifying AWS credentials..."
        aws sts get-caller-identity
