name: Inject demo.tfvars

inputs:
  tfvars:
    required: false

runs:
  using: composite
  steps:

    - name: inject demo.tfvars
      shell: bash
      run: |
        # checkout/inject-demo-tfvars
        cat << EOF >> demo.tfvars
        ${{ inputs.tfvars }}
        EOF
        echo "demo.tfvars:"
        cat demo.tfvars
