name: Init

inputs:
  github_inputs:
    required: false
  github_vars:
    required: false
  github_token:
    required: false
  personal_access_token:
    required: false
  show_github_env:
    required: false
  terraform_app_id:
    required: false
  terraform_private_key:
    required: false

outputs:
  env_json:
    value: ${{ steps.set-github-output.outputs.env_json }}

runs:
  using: composite
  steps:

    - name: set github env
      if: inputs.github_inputs != '' || inputs.github_vars != ''
      id: set-github-env
      uses: stormreply/slt-workflows/.github/actions/init/set-github-env@main
      with:
        github_inputs: ${{ inputs.github_inputs }}
        github_vars: ${{ inputs.github_vars }}

    - name: set token
      if: inputs.github_token != '' || inputs.personal_access_token != '' || inputs.terraform_app_id != ''
      id: set-token
      uses: stormreply/slt-workflows/.github/actions/init/set-token@main
      with:
        github_token: ${{ inputs.github_token }}
        personal_access_token: ${{ inputs.personal_access_token }}
        terraform_app_id: ${{ inputs.terraform_app_id }}
        terraform_private_key: ${{ inputs.terraform_private_key }}

    - name: set github output
      if: inputs.github_inputs != '' || inputs.github_vars != ''
      id: set-github-output
      uses: stormreply/slt-workflows/.github/actions/init/set-github-output@main

    - name: show github env
      if: vars.DEBUG == 'true'
      id: show-github-env
      uses: stormreply/slt-workflows/.github/actions/init/show-github-env@main
