name: Check code

inputs:
  publish_badge:
    required: false

runs:
  using: composite
  steps:

    - name: checkout code
      uses: stormreply/slt-workflows/.github/actions/terraform/checkout@main

    - name: check code
      id: check-code
      shell: bash
      run: |
        # check/code (pre-commit-terraform)
        docker run \
          --entrypoint /bin/bash \
          -e "USERID=$(id -u):$(id -g)" \
          -e "TOKEN=${{ env.TOKEN }}" \
          -v $(pwd):/lint \
          -w /lint \
          ghcr.io/antonbabenko/pre-commit-terraform:latest -c '
            git config --global url."https://x-access-token:$TOKEN@github.com/".insteadOf "https://github.com/"
            # git config --global url."https://x-access-token:$TOKEN@github.com/".insteadOf "git@github.com:"
            # git config --list --show-origin
            terraform --version
            pre-commit run -a
          '

    - name: fix permissions
      if: always()
      shell: bash
      run: sudo chown -R "$(id -u):$(id -g)" .

    - name: publish badge
      if: inputs.publish_badge == 'true'
      uses: stormreply/slt-workflows/.github/actions/badges@main
      with:
        file: check-code.json
        label: "Check Code"
        message: ${{ steps.check-code.outcome == 'success' && 'passing' || 'failing' }}
        score: ${{ steps.check-code.outcome == 'success' && '1' || '0' }}
