name: Set environment vars

inputs:
  github_token:
    required: false
  personal_access_token:
    required: false
  terraform_private_key:
    required: false
  json:
    required: false
  yaml:
    required: false
  show:
    required: false

runs:
  using: composite
  steps:

    - name: Time
      shell: bash
      run: date | tee -a $GITHUB_STEP_SUMMARY

    - name: set environment from secrets
      id: set-environment-from-secrets
      uses: stormreply/slt-workflows/.github/actions/set-environment/from-secrets@main
      with:
        github_token: ${{ inputs.github_token }}
        personal_access_token: ${{ inputs.personal_access_token }}
        terraform_private_key: "${{ inputs.terraform_private_key }}"

    - name: set environment from vars
      if: inputs.json != ''
      id: set-environment-from-vars
      uses: stormreply/slt-workflows/.github/actions/set-environment/from-vars@main
      with:
        json: ${{ inputs.json }}

    - name: set environment from inputs
      if: inputs.yaml != ''
      id: set-environment-from-inputs
      uses: stormreply/slt-workflows/.github/actions/set-environment/from-inputs@main
      with:
        yaml: ${{ inputs.yaml }}

    - name: set environment from others
      id: set-environment-from-others
      uses: stormreply/slt-workflows/.github/actions/set-environment/from-others@main

    - name: set github output
      id: set-github-output
      uses: stormreply/slt-workflows/.github/actions/set-environment/set-github-output@main

    - name: set step summary
      if: inputs.show != ''
      id: set-github-step-summary
      uses: stormreply/slt-workflows/.github/actions/set-environment/set-step-summary@main
