name: Set environment vars

inputs:
  action:
    required: false
  github_inputs:
    required: false
  github_vars:
    required: false
  infracost_api_key:
    required: false

outputs:
  env_json:
    value: ${{ steps.set-github-output.outputs.env_json }}

runs:
  using: composite
  steps:

    - name: Time
      shell: bash
      run: date

    - name: set environment from vars
      if: inputs.github_vars != ''
      id: set-environment-from-vars
      uses: stormreply/slt-workflows/.github/actions/set-environment/from-vars@main
      with:
        github_vars: ${{ inputs.github_vars }}

    - name: set environment from inputs
      if: inputs.github_inputs != ''
      id: set-environment-from-inputs
      uses: stormreply/slt-workflows/.github/actions/set-environment/from-inputs@main
      with:
        github_inputs: ${{ inputs.github_inputs }}

    - name: set environment from others
      id: set-environment-from-others
      uses: stormreply/slt-workflows/.github/actions/set-environment/from-others@main

    - name: set github output
      id: set-github-output
      uses: stormreply/slt-workflows/.github/actions/set-environment/set-github-output@main

    - name: set step summary
      if: inputs.action != ''
      id: set-github-step-summary
      uses: stormreply/slt-workflows/.github/actions/set-environment/set-step-summary@main
