name: Check

permissions:
  contents: write
  id-token: write

on:
  workflow_call:
    secrets:
      INFRACOST_API_KEY:
        required: false
      STORM_LIBRARY_FOR_TERRAFORM:
        required: false
      TERRAFORM_PRIVATE_KEY:
        required: false

jobs:

  files:
    runs-on: ubuntu-latest
    steps:

      - name: set environment
        id: set-environment
        uses: stormreply/slt-workflows/.github/actions/set-environment@main
        with:
          action: check
          github_vars: "${{ toJson(vars) }}"

      - name: check files
        id: check-files
        uses: stormreply/slt-workflows/.github/actions/check/files@main
        with:
          exit_on_fail: false
          publish_badge: true
          personal_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

  code:
    runs-on: ubuntu-latest
    steps:

      - name: set environment
        id: set-environment
        uses: stormreply/slt-workflows/.github/actions/set-environment@main
        with:
          action: check
          github_vars: "${{ toJson(vars) }}"

      - name: check code
        uses: stormreply/slt-workflows/.github/actions/check/code@main
        with:
          publish_badge: true
          personal_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
          token_notice: true

  compliance:
    runs-on: ubuntu-latest
    steps:

      - name: set environment
        id: set-environment
        uses: stormreply/slt-workflows/.github/actions/set-environment@main
        with:
          action: check
          github_vars: "${{ toJson(vars) }}"

      - name: check compliance
        uses: stormreply/slt-workflows/.github/actions/check/compliance@main
        with:
          publish_badge: true
          personal_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
