name: Configure

on:
  workflow_call:
    # checkov:skip=CKV_GHA_7: "GitHub Actions workflow_dispatch inputs MUST be empty"
    inputs:
      access_domain:
        description: "Access domain"
        type: string
      access_role:
        description: "Access role"
        type: string
      backend_account:
        description: "Backend account"
        type: string
      backend_region:
        description: "Backend region"
        type: string
      oidc_principal:
        description: "OIDC principal"
        type: string
    secrets:
      # NOTE: GITHUB_TOKEN can NOT set github variables (like BACKEND_ACCOUNT)
      STORM_LIBRARY_FOR_TERRAFORM:
        required: false
      TERRAFORM_PRIVATE_KEY:
        required: false

permissions:
  actions: write
  contents: read

jobs:

  init:
    runs-on: ubuntu-latest
    outputs:
      env_json: ${{ steps.set-environment.outputs.env_json }}
    steps:

      # TODO: add step HERE to check if PAT or APP TOKEN available. GITHUB_TOKEN is NOT sufficient
      - name: check token
        id: check-token
        shell: bash
        run: |
          # check-token
          if [ -z "${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}" -a -z "${{ secrets.TERRAFORM_PRIVATE_KEY }}" ] ; then
            echo "::error ::It seems like you have no valid token."
            exit 1
          fi

      - name: set environment
        id: set-environment
        uses: stormreply/slt-workflows/.github/actions/set-environment@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          personal_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
          json: "${{ toJson(vars) }}"
          yaml: |
            ACCESS_DOMAIN: ${{ inputs.access_domain || vars.ACCESS_DOMAIN }}
            ACCESS_ROLE: ${{ inputs.access_role || vars.ACCESS_ROLE }}
            BACKEND_ACCOUNT: ${{ inputs.backend_account || vars.BACKEND_ACCOUNT }}
            BACKEND_REGION: ${{ inputs.backend_region || vars.BACKEND_REGION }}
            DEPLOYMENT_ACCOUNT: ${{ inputs.backend_account || vars.BACKEND_ACCOUNT }}
            DEPLOYMENT_REGION: ${{ inputs.backend_region || vars.BACKEND_REGION }}
            ENVIRONMENT: ${{ github.actor }}
            OIDC_PRINCIPAL: ${{ inputs.oidc_principal || vars.OIDC_PRINCIPAL || github.repository_owner }}
          show: init

      - name: save variables in ${{github.repository}}
        uses: stormreply/slt-workflows/.github/actions/configure/init/save-variables@main
        with:
          repository: ${{ github.repository }}

  sso:
    needs: init
    runs-on: ubuntu-latest
    outputs:
      access_token: ${{ steps.get-access-token.outputs.access_token }}
    env: ${{ fromJson(needs.init.outputs.env_json) }}
    steps:

      - name: get access token
        id: get-access-token
        uses: stormreply/slt-workflows/.github/actions/configure/sso/get-access-token@main

  build:
    needs: [init, sso]
    runs-on: ubuntu-latest
    env: ${{ fromJson(needs.init.outputs.env_json) }}
    steps:

      - name: set backend credentials
        uses: stormreply/slt-workflows/.github/actions/configure/sso/set-backend-credentials@main
        with:
          access_token: ${{ needs.sso.outputs.access_token }}

      - name: create backend bucket
        uses: stormreply/slt-workflows/.github/actions/configure/boot/create-backend-bucket@main

      - name: checkout code
        uses: stormreply/slt-workflows/.github/actions/terraform/checkout@main
        with:
          init: true

  #     - name: Terraform plan
  #       uses: stormreply/slt-workflows/.github/actions/terraform/plan@main
  #       with:
  #         var_file: init.tfvars

  #     - name: Terraform apply
  #       uses: stormreply/slt-workflows/.github/actions/terraform/apply@main
  #       with:
  #         var_file: init.tfvars
