name: Configure

on:
  workflow_call:
    # checkov:skip=CKV_GHA_7: "GitHub Actions workflow_dispatch inputs MUST be empty"
    inputs:
      access_domain:
        description: "AWS Access Domain"
        type: string
      access_role:
        description: "AWS Access Role"
        type: string
      backend_account:
        description: "Terraform Backend Account"
        type: string
      backend_region:
        description: "Terraform Backend Region"
        type: string
    secrets:
      STORM_LIBRARY_FOR_TERRAFORM:
        required: false
      TERRAFORM_PRIVATE_KEY:
        required: false

permissions:
  actions: write
  contents: read

jobs:

  init:
    runs-on: ubuntu-latest
    outputs:
      env_json: ${{ steps.set-environment.outputs.env_json }}
    steps:

      - name: set token
        id: set-token
        uses: stormreply/slt-workflows/.github/actions/set-token@main
        with:
          personal_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: set environment
        id: set-environment
        uses: stormreply/slt-workflows/.github/actions/set-environment@main
        with:
          github_vars: "${{ toJson(vars) }}"
          github_inputs: |
            ACCESS_DOMAIN: ${{ inputs.access_domain || vars.ACCESS_DOMAIN }}
            ACCESS_ROLE: ${{ inputs.access_role || vars.ACCESS_ROLE }}
            BACKEND_ACCOUNT: ${{ inputs.backend_account || vars.BACKEND_ACCOUNT }}
            BACKEND_REGION: ${{ inputs.backend_region || vars.BACKEND_REGION }}
            DEPLOYMENT_ACCOUNT: ${{ inputs.backend_account || vars.BACKEND_ACCOUNT }}
            DEPLOYMENT_REGION: ${{ inputs.backend_region || vars.BACKEND_REGION }}
            OIDC_PRINCIPAL: ${{ github.repository_owner }}
          show: init

      - name: save variables in ${{github.repository}}
        uses: stormreply/slt-workflows/.github/actions/configure/init/save-variables@main
        with:
          repository: ${{ github.repository }}

  sso:
    needs: init
    runs-on: ubuntu-latest
    outputs:
      access_token: ${{ steps.get-access-token.outputs.access_token }}
    env: ${{ fromJson(needs.init.outputs.env_json) }}
    steps:

      - name: get access token
        id: get-access-token
        uses: stormreply/slt-workflows/.github/actions/configure/sso/get-access-token@main

  build:
    needs: [init, sso]
    runs-on: ubuntu-latest
    env: ${{ fromJson(needs.init.outputs.env_json) }}
    steps:

      - name: set token
        id: set-token
        uses: stormreply/slt-workflows/.github/actions/set-token@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          personal_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: set backend credentials
        uses: stormreply/slt-workflows/.github/actions/configure/build/set-backend-credentials@main
        with:
          access_token: ${{ needs.sso.outputs.access_token }}

      - name: create backend bucket
        uses: stormreply/slt-workflows/.github/actions/configure/build/create-backend-bucket@main

      - name: create github oidc provider
        uses: stormreply/slt-workflows/.github/actions/configure/build/create-github-oidc-provider@main

      - name: checkout code
        uses: stormreply/slt-workflows/.github/actions/terraform/checkout@main
        with:
          init: true

      - name: Terraform plan
        uses: stormreply/slt-workflows/.github/actions/terraform/plan@main
        with:
          var_file: init.tfvars

      - name: Terraform apply
        uses: stormreply/slt-workflows/.github/actions/terraform/apply@main
        # with:
        #   var_file: init.tfvars
