name: Configure v2

on:
  workflow_call:
    # checkov:skip=CKV_GHA_7: "GitHub Actions workflow_dispatch inputs MUST be empty"
    inputs:
      configuration_target:
        type: string
      account_id:
        type: string
      region:
        type: string
      aws_access_key_id:
        type: string
      aws_secret_access_key:
        type: string
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: aws login
        id: aws-login
        uses: stormreply/slt-workflows/.github/actions/configure/login@main
        with:
          region: ${{ inputs.region }}
          aws-access-key-id: ${{ inputs.aws_access_key_id }}
          aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
