name: Configure v2

on:
  workflow_call:
    # checkov:skip=CKV_GHA_7: "GitHub Actions workflow_dispatch inputs MUST be empty"
    inputs:
      access_domain:
        type: string
      permission_set:
        type: string
      account_id:
        type: string
      region:
        type: string
      sso:
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false

jobs:

  sso:
    if: inputs.sso == 'true'
    runs-on: ubuntu-latest
    outputs:
      ACCESS_TOKEN: ${{ steps.get-access-token.outputs.ACCESS_TOKEN }}
    steps:
      - name: get access token
        id: get-access-token
        uses: stormreply/slt-workflows/.github/actions/configure/sso/get-access-token@main
        with:
          access_domain: ${{ inputs.access_domain }}
          region: ${{ inputs.region }}

  access:
    if: always()
    needs: sso
    runs-on: ubuntu-latest
    outputs:
      AWS_ACCESS_KEY_ID:     ${{ steps.get-credentials.outputs.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ steps.get-credentials.outputs.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:     ${{ steps.get-credentials.outputs.AWS_SESSION_TOKEN }}
      AWS_DEFAULT_REGION:    ${{ steps.get-credentials.outputs.AWS_DEFAULT_REGION }}
    steps:

      - name: get-credentials-from-identity-center
        if: inputs.sso == 'true'
        id: get-credentials
        uses: stormreply/slt-workflows/.github/actions/configure/sso/get-credentials@main
        with:
          access_token: ${{ needs.sso.outputs.ACCESS_TOKEN }}
          account_id: ${{ inputs.account_id }}
          permission_set: ${{ inputs.permission_set }}
          region: ${{ inputs.region }}

      - name: get-credentials
        shell: bash
        run: |
          # configure-v2/get-credentials

          if [[ "${{ inputs.sso }}" == "true" ]] ; then
            cat << EOF >> $GITHUB_OUTPUT
            AWS_ACCESS_KEY_ID=${{ steps.get-credentials.outputs.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ steps.get-credentials.outputs.AWS_SECRET_ACCESS_KEY }}
            AWS_SESSION_TOKEN=${{ steps.get-credentials.outputs.AWS_SESSION_TOKEN }}
            AWS_DEFAULT_REGION=${{ steps.get-credentials.outputs.AWS_DEFAULT_REGION }}
          EOF
          else
            cat << EOF >> $GITHUB_OUTPUT
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION=${{ inputs.region }}
          EOF
          fi

  build:
    needs: access
    runs-on: ubuntu-latest
    steps:

      - name: Verify AWS Identity
        shell: bash
        run: |
          echo "Verifying AWS credentials..."
          aws sts get-caller-identity

      # - name: create backend bucket
      #   uses: stormreply/slt-workflows/.github/actions/configure/build/create-backend-bucket@main

      # - name: create github oidc provider
      #   uses: stormreply/slt-workflows/.github/actions/configure/build/create-github-oidc-provider@main

      # - name: checkout code
      #   uses: stormreply/slt-workflows/.github/actions/terraform/checkout@main
      #   with:
      #     init: true

      # - name: Terraform plan
      #   uses: stormreply/slt-workflows/.github/actions/terraform/plan@main
      #   with:
      #     var_file: init.tfvars

      # - name: Terraform apply
      #   uses: stormreply/slt-workflows/.github/actions/terraform/apply@main
      #   # with:
      #   #   var_file: init.tfvars
