name: Settings

on:
  workflow_call:
    # checkov:skip=CKV_GHA_7: "GitHub Actions workflow_dispatch inputs MUST be empty"
    secrets:
      INFRACOST_API_KEY:
        required: false
      STORM_LIBRARY_FOR_TERRAFORM:
        required: false
      TERRAFORM_PRIVATE_KEY:
        required: false

permissions:
  actions: write
  contents: read

jobs:

  settings:
    runs-on: ubuntu-latest
    steps:

      - name: init
        id: init
        uses: stormreply/slt-workflows/.github/actions/init@main
        with:
          action: settings
          github_vars: "${{ toJson(vars) }}"
          github_token: ${{ secrets.GITHUB_TOKEN}}
          personal_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
          token_notice: true
