name: Test

permissions:
  contents: read
  id-token: write

on:
  workflow_call:
    secrets:
      INFRACOST_API_KEY:
        required: false
      STORM_LIBRARY_FOR_TERRAFORM:
        required: false
      TERRAFORM_PRIVATE_KEY:
        required: false

jobs:

  check:
    runs-on: ubuntu-latest
    steps:

      - name: Time
        shell: bash
        run: date

      - name: init
        id: init
        uses: stormreply/slt-workflows/.github/actions/init@main
        with:
          github_vars: "${{ toJson(vars) }}"
          personal_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
          show_github_env: true

      - name: check code
        uses: stormreply/slt-workflows/.github/actions/check/code@main

  plan:
    runs-on: ubuntu-latest
    outputs:
      env_json: ${{ steps.init.outputs.env_json }}
    steps:

      - name: init
        id: init
        uses: stormreply/slt-workflows/.github/actions/init@main
        with:
          github_vars: "${{ toJson(vars) }}"
          personal_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: plan
        uses: stormreply/slt-workflows/.github/actions/plan@main
        with:
          infracost_api_key: ${{ secrets.INFRACOST_API_KEY }}

  apply:
    needs: plan
    runs-on: ubuntu-latest
    env: ${{ fromJson(needs.plan.outputs.env_json) }}
    steps:

      - name: init
        id: init
        uses: stormreply/slt-workflows/.github/actions/init@main
        with:
          personal_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: apply
        uses: stormreply/slt-workflows/.github/actions/apply@main

  destroy:
    needs: [plan, apply]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    env: ${{ fromJson(needs.plan.outputs.env_json) }}
    steps:

      - name: init
        id: init
        uses: stormreply/slt-workflows/.github/actions/init@main
        with:
          personal_access_token: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
          terraform_app_id: ${{ vars.TERRAFORM_APP_ID }}
          terraform_private_key: ${{ secrets.TERRAFORM_PRIVATE_KEY }}

      - name: destroy
        uses: stormreply/slt-workflows/.github/actions/destroy@main

      - name: unschedule actions
        uses: stormreply/slt-workflows/.github/actions/unschedule@main
        with:
          action: ".*"
        continue-on-error: true
